version: '3.7'

services:
  pushserver:
    build:
      context: ./
      dockerfile: ./docker/dev.Dockerfile
    env_file:
      - ./.env
    image: 
    restart: on-failure
    depends_on:
      - mongodb
    ports:
      - '5000:8000'
    environment:
      SERVER_PORT: 8000
    volumes:
      - ./src:/home/node/src
      - ./certs:/home/node/certs
      - ./logs:/home/node/logs
    command: ['npm', 'run', 'dev']

  mongodb:
    image: mongo:4.0
    restart: on-failure
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: ~
